# Use the official Nginx image as the base image
FROM nginx:latest

# Copy custom nginx configuration file
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy project files
COPY . /var/www/html